"""travel_add_province

Revision ID: 621cd0f3b85f
Revises: 75475cf27a09
Create Date: 2024-04-07 20:59:40.122275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '621cd0f3b85f'
down_revision: Union[str, None] = '75475cf27a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('travel_province', sa.String(length=30), nullable=False))
    op.alter_column('travel', 'travel_place',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=300),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('travel', 'travel_place',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=300),
               existing_nullable=False)
    op.drop_column('travel', 'travel_province')
    # ### end Alembic commands ###
