"""del_tra_int_uni

Revision ID: 80c722ce54d4
Revises: 621cd0f3b85f
Create Date: 2024-04-07 22:40:00.416231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80c722ce54d4'
down_revision: Union[str, None] = '621cd0f3b85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('albumtype_name', table_name='album_type')
    op.drop_index('travel_album_name', table_name='travel')
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index('travel_album_name', 'travel', ['travel_album_name'], unique=True)
    op.create_index('albumtype_name', 'album_type', ['albumtype_name'], unique=True)
    # ### end Alembic commands ###
