"""updatatables

Revision ID: ac3da8f7929e
Revises: dc8d228c33e7
Create Date: 2024-04-18 17:41:43.493446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac3da8f7929e'
down_revision: Union[str, None] = 'dc8d228c33e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_name', sa.String(length=50), nullable=False),
    sa.Column('video_date', sa.DateTime(), nullable=False),
    sa.Column('video_size', sa.String(length=20), nullable=False),
    sa.Column('video_nickname', sa.String(length=50), nullable=True),
    sa.Column('video_specifc_event', sa.Integer(), nullable=False),
    sa.Column('video_owner', sa.String(length=15), nullable=True),
    sa.Column('video_album_type', sa.Integer(), nullable=True),
    sa.Column('video_album', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_album'], ['album.id'], ),
    sa.ForeignKeyConstraint(['video_album_type'], ['album_type.id'], ),
    sa.ForeignKeyConstraint(['video_owner'], ['user.baidu_uk'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_name')
    )
    op.create_index(op.f('ix_video_id'), 'video', ['id'], unique=False)
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_video_id'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
