"""video_up_column4

Revision ID: aff283eb49c9
Revises: e54644c06dc4
Create Date: 2024-04-15 21:13:45.505173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aff283eb49c9'
down_revision: Union[str, None] = 'e54644c06dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('video', sa.Column('video_album_type', sa.Integer(), nullable=True))
    op.drop_constraint('video_ibfk_2', 'video', type_='foreignkey')
    op.create_foreign_key(None, 'video', 'album_type', ['video_album_type'], ['id'])
    op.drop_column('video', 'vide_album_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('vide_album_type', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_foreign_key('video_ibfk_2', 'video', 'album_type', ['vide_album_type'], ['id'])
    op.drop_column('video', 'video_album_type')
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
