"""revise-tow-modle

Revision ID: ba3859b8f107
Revises: 8ff92975e197
Create Date: 2024-03-06 15:33:19.227498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba3859b8f107'
down_revision: Union[str, None] = '8ff92975e197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('album', 'album_type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'album', 'album_type', ['album_type'], ['id'])
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.alter_column('album', 'album_type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
