"""user_taken

Revision ID: da139570e913
Revises: 8b48e49c9e64
Create Date: 2024-01-29 12:20:36.821420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da139570e913'
down_revision: Union[str, None] = '8b48e49c9e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(length=500), nullable=False))
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('ix_user_baidu_uk'), 'user', ['baidu_uk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_baidu_uk'), table_name='user')
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
