"""video_up_column

Revision ID: e6151d7311e8
Revises: 096aff70d366
Create Date: 2024-04-15 11:06:19.515771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6151d7311e8'
down_revision: Union[str, None] = '096aff70d366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('video', sa.Column('video_nickname', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'video', ['video_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_column('video', 'video_nickname')
    op.alter_column('user', 'id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
